---
  - name: Running playbooks
    hosts: all
    become: true
    become_method: sudo
    vars_files: vms.yaml

    tasks:
      - include: install_kvm_and_dependencies_playbook.yaml
  - name: netvm_imp
    import_playbook: net_and_vm.yaml
